export default
    {

      about: {
        title: 'Sobre Mim',
        content: '<p>Me chamo Nathana.&nbsp;</p> <p>Sou uma pessoa curiosa e que adora novas ideias. Ao mesmo tempo, me preocupo muito com pessoas. Acredito que todo mundo tem sua forma de fazer a diferen&ccedil;a na vida das pessoas, ent&atilde;o com meus projetos tento fazer o m&aacute;ximo disso.</p> <p>Embora boa parte dos meus projetos est&atilde;o relacionados com escrever, a minha forma&ccedil;&atilde;o &eacute; Ci&ecirc;ncias da Computa&ccedil;&atilde;o. N&atilde;o me importo em me aventurar em &aacute;rea diferente dessa, mas tenho uma paix&atilde;o por n&uacute;meros e programar tamb&eacute;m.</p> <p>Fiz especializa&ccedil;&atilde;o e mestrado na &aacute;rea. Tudo isso em universidade p&uacute;blica, o que significa que eu sempre me esforcei muito para alcan&ccedil;ar os meus sonhos.&nbsp;</p> <p><br></p> <p><strong>Blog da Nana</strong></p> <p>Espero que esse pequeno blog possa ajudar outras pessoas encontrar conte&uacute;do que agregue algo a elas. Pensei em focar s&oacute; em programa&ccedil;&atilde;o, mas da&iacute; pensei um pouco mais e resolvi focar em tudo que achar no caminho que eu percorrer. Afinal a vida &eacute; feito de tantas coisas, porque limitar quando podemos expandir?</p> <p><br></p> <p><strong>Contato</strong></p> <p>Caso precise entrar em contato, me mande um e-mail: nathanafacion@gmail.com</p> <p><br></p>'
      },
      contact: {
        title: 'Contato',
        content: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. <br><br> Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.'
      },
      garotaNoControle: {
        title: 'Projeto: Garota no Controle',
        content: '<p style="text-align: justify;">O site <a href="https://garotanocontrole.com.br/">Garota no Controle</a> &eacute; um site independente que surgiu em 2020 com o objetivo de apresentar a vis&atilde;o de uma garota gamer sobre o mundo dos jogos.</p> <p style="text-align: justify;">A maioria do p&uacute;blico gamer hoje &eacute; constitu&iacute;do de homens, ent&atilde;o, embora o site tenha sido feito para todas as pessoas, um dos principais objetivos &eacute; fazer com que mais mulheres possam vir a gostar do assunto, ou at&eacute; mesmo que tenham mais coragem para expor suas opini&otilde;es sobre.</p> <p style="text-align: justify;">Com apenas um ano, nossa equipe j&aacute; tem14 pessoas e recebemos apoio de empresas grandes e pequenas para conseguir jogos para an&aacute;lises e assim manter o site.</p> <p style="text-align: justify;">Voc&ecirc; encontrar&aacute; os seguintes conte&uacute;dos no site:</p> <ul> <li style="text-align:justify;">An&aacute;lises: para ajudar o leitor a conhecer novos jogos, ou saber se um jogo pode ser do seu agrado, ou n&atilde;o. E para ajudar principalmente na visibilidade de jogos indies.</li> <li style="text-align: justify;">Listas: uma an&aacute;lise sobre algum assunto, que gera uma lista com o objetivo de classificar baseado em algum crit&eacute;rio. Com isso, quero incentivar o leitor a pensar qual a classifica&ccedil;&atilde;o que ele mesmo faria e gerar uma reflex&atilde;o, ou discuss&atilde;o sobre o assunto</li> <li style="text-align: justify;">Curiosidades: s&atilde;o escolhidos assuntos incomuns para serem abordados e instigar a curiosidade do leitor. Em muitos casos, os artigos selecionados s&atilde;o cient&iacute;ficos, para o leitor perceber que a import&acirc;ncia dos jogos est&atilde;o em todos os lugares.</li> <li style="text-align: justify;">Entrevista: s&atilde;o feitas com profissionais da &aacute;rea de jogos para divulgar trabalhos menos conhecidos. &Eacute; uma oportunidade de fazer os usu&aacute;rios se interessarem por jogos de menor or&ccedil;amento. Esse site quer apoiar os jogos indies, principalmente os brasileiros.</li> </ul>'
      },
      vimLiVenci: {
        title: 'Projeto: Vim Li Venci',
        content: '<p style="text-align: justify;">Este projeto ainda est&aacute; em desenvolvimento, ou seja, est&aacute; nas fases onde estou determinando quais objetivos quero alcan&ccedil;ar com ele.</p> <p style="text-align: justify;">Como sempre gostei de ler, queria conseguir uma forma de ajudar outras pessoas a terem o gosto pela leitura e mais acesso a livros.</p> <p style="text-align: justify;">Para isso, o que tenho de ideias iniciais seria:</p> <ul> <li style="text-align: justify;">Entrevistas com autores nacionais para entender como funciona o mercado atual e ajudar novos escritores a alcan&ccedil;ar seus sonhos.</li>  <li style="text-align: justify;">Divulga&ccedil;&atilde;o de v&aacute;rios tipos de livros, inclusive os independentes.</li> <li style="text-align: justify;">Trazer as principais novidades liter&aacute;rias, inclusive independentes.</li>  <li style="text-align: justify;">Resenhas de livros lidos pelos integrantes.</li>  <li style="text-align: justify;">Arrecadar livros para distribuir entre comunidade de baixa renda. Caso eu receba livros de editoras para divulgar e fazer resenhas, me comprometo a doa-los ap&oacute;s a leitura e divulga&ccedil;&atilde;o.</li> </ul>'
      }

    };
